version: '2.1'

services:
  ip-anomoly-detection:
    image: ip-anomoly-detection
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    links:
      - redis

  redis:
    image: redis
    ports:
      - 6379:6379
